# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee48c9ef92833c549bedfd452b57416d6e829bd214e2fbe0d2773d613ff0a661d88aed7fee8be8ce02994069035f5a83ca9e6bc0119f8eb7eee217ee89433ed

test:
  secret_key_base: a75e33400d1fda465404d67d7b5d7df28290ecb6489d3b24552ebcbad80f6feb3af73415a5ff3393306823e32bdfbeae2cbf011128e4e0e7dd8d8c2feca0b5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
